_format_version: "3.0"

plugins:
  - name: cors
    config:
      origins:
        - http://localhost:3000
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
        - PATCH
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - X-Auth-Token
        - Authorization
      credentials: true

services:
  - name: auth-service
    url: http://host.docker.internal:4001
    routes:
      - name: auth-route
        paths:
          - /api/auth
        strip_path: false

  - name: user-service
    url: http://host.docker.internal:4002
    routes:
      - name: user-route
        paths:
          - /api/user
          - /api/account
        strip_path: false

  - name: market-service
    url: http://host.docker.internal:4005
    routes:
      - name: market-route
        paths:
          - /api/market
        strip_path: false

  - name: news-service
    url: http://host.docker.internal:4003
    routes:
      - name: news-route
        paths:
          - /api/news
        strip_path: false

  - name: news-ai-service
    url: http://host.docker.internal:4004
    routes:
      - name: news-ai-route
        paths:
          - /api/prediction
          - /api/training
        strip_path: false

  - name: plan-service
    url: http://host.docker.internal:4006
    routes:
      - name: plan-route
        paths:
          - /api/plans
        strip_path: false

  - name: payment-service
    url: http://host.docker.internal:4005
    routes:
      - name: payment-route
        paths:
          - /api/payments
        strip_path: false

  - name: subscription-service
    url: http://host.docker.internal:4007
    routes:
      - name: subscription-route
        paths:
          - /api/subscriptions
        strip_path: false
